# Generated by Django 3.1.7 on 2021-03-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(default='default.svg', upload_to='profile_pics'),
        ),
    ]
